name: tr_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas=0.25.0
  - matplotlib
  - r-base=3.6.1
  - r-dplr
  - numpy=1.17.0
  - pip
  - pip:
    - rpy2==2.9.5
    - tzlocal==2.0.0
