#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
树种代码到拉丁名的映射表
为allometric_dict.py和allometric_dict_species.py提供服务
"""

# 树种代码到拉丁名的完整映射表
SPECIES_CODE_MAP = {
    # 针叶树 - Abies属（冷杉）
    'ABAM': 'Abies amabilis',  # 太平洋银冷杉
    'ABBA': 'Abies balsamea',  # 香脂冷杉
    'ABCO': 'Abies concolor',  # 白冷杉
    'ABLA': 'Abies lasiocarpa', # 高山冷杉
    'ABMA': 'Abies magnifica', # 壮丽冷杉
    
    # 针叶树 - Picea属（云杉）
    'PCAB': 'Picea abies',    # 欧洲云杉
    'PCEN': 'Picea engelmannii', # 恩氏云杉
    'PCGL': 'Picea glauca',   # 白云杉
    'PCMA': 'Picea mariana',  # 黑云杉
    'PCPU': 'Picea pungens',  # 刺云杉
    'PCRU': 'Picea rubens',   # 红云杉
    'PCSI': 'Picea sitchensis', # 西茨卡云杉
    
    # 针叶树 - Pinus属（松树）
    'PIAL': 'Pinus albicaulis', # 白皮松
    'PIAR': 'Pinus aristata',  # 刚毛松
    'PIBA': 'Pinus banksiana', # 矮松
    'PIBN': 'Pinus banksiana', # 矮松（同上）
    'PICE': 'Pinus cembroides', # 墨西哥松
    'PICO': 'Pinus contorta',  # 扭叶松
    'PIED': 'Pinus edulis',    # 可食松
    'PIEC': 'Pinus echinata',  # 短叶松
    'PIFL': 'Pinus flexilis',  # 柔软松
    'PIJE': 'Pinus jeffreyi',  # 杰佛里松
    'PILA': 'Pinus lambertiana', # 糖松
    'PILO': 'Pinus leiophylla', # 光叶松
    'PIMR': 'Pinus monticola', # 西部白松
    'PINI': 'Pinus nigra',     # 黑松
    'PIPA': 'Pinus palustris', # 长叶松
    'PIPI': 'Pinus pinea',     # 意大利石松
    'PIPN': 'Pinus pinaster',  # 海岸松
    'PIPO': 'Pinus ponderosa', # 西黄松
    'PIPU': 'Pinus pungens',   # 刺松
    'PIRE': 'Pinus resinosa',  # 赤松
    'PIRI': 'Pinus rigida',    # 刚松
    'PISF': 'Pinus strobiformis', # 墨西哥白松
    'PIST': 'Pinus strobus',   # 美国白松
    'PISY': 'Pinus sylvestris', # 欧洲赤松
    'PITA': 'Pinus taeda',     # 火炬松
    'PITO': 'Pinus torreyana', # 托里松
    'PIVI': 'Pinus virginiana', # 弗吉尼亚松
    'PISP': 'Pinus',           # 松属（通用）
    'PINE': 'Pinus',           # 松属（通用）
    
    # 阔叶树 - 栎属（橡树、栎树）
    'QUAL': 'Quercus alba',    # 白栎
    'QUCO': 'Quercus coccinea', # 猩红栎
    'QUCF': 'Quercus',         # 栎属（通用）
    'QUDG': 'Quercus douglasii', # 道格拉斯栎
    'QUFA': 'Quercus falcata',  # 南方红栎
    'QULO': 'Quercus lobata',   # 加州谷栎
    'QULY': 'Quercus lyrata',   # 漂栎
    'QUMA': 'Quercus macrocarpa', # 大果栎
    'QUMU': 'Quercus muehlenbergii', # 栗栎
    'QUPA': 'Quercus palustris', # 沼栎
    'QUPE': 'Quercus petraea',   # 冬栎
    'QURO': 'Quercus robur',     # 夏栎
    'QURU': 'Quercus rubra',     # 北方红栎
    'QUSH': 'Quercus shumardii', # 舒马德栎
    'QUST': 'Quercus stellata',  # 柱栎
    'QUVE': 'Quercus velutina',  # 黑栎
    'QUSP': 'Quercus',           # 栎属（通用）
    
    # 阔叶树 - 其他
    'ACRU': 'Acer rubrum',       # 红枫
    'ACSH': 'Acer saccharum',    # 糖枫
    'BELE': 'Betula lenta',      # 樱桦
    'BEPE': 'Betula pendula',    # 垂枝桦
    'BEPU': 'Betula pubescens',  # 白桦
    'CADE': 'Calocedrus decurrens', # 加州香柏
    'CADN': 'Castanopsis densiflora', # 密花栲
    'CASA': 'Castanea sativa',   # 欧洲栗
    'CDLI': 'Cedrus libani',     # 黎巴嫩雪松
    'CHLA': 'Chamaecyparis lawsoniana', # 劳森柏
    'CHNO': 'Chamaecyparis nootkatensis', # 黄柏
    'CYGL': 'Cyperus glaber',     # 光籽莎草
    'CYOV': 'Cyperus ovatus',     # 卵形莎草
    'FAGR': 'Fagus grandifolia',  # 美洲山毛榉
    'FASY': 'Fagus sylvatica',    # 欧洲山毛榉
    'JUOC': 'Juniperus occidentalis', # 西部刺柏
    'JUOS': 'Juniperus osteosperma', # 犹他刺柏
    'JUSC': 'Juniperus scopulorum', # 落基山刺柏
    'JUVI': 'Juniperus virginiana', # 弗吉尼亚刺柏
    'LADE': 'Larix decidua',       # 欧洲落叶松
    'LALA': 'Larix laricina',      # 美洲落叶松
    'LALY': 'Larix lyallii',       # 高山落叶松
    'LAOC': 'Larix occidentalis',  # 西方落叶松
    'LIDE': 'Lithocarpus densiflorus', # 紧花石栎
    'LITU': 'Liriodendron tulipifera', # 北美鹅掌楸
    'MIXD': 'Mixed species',        # 混合树种
    'PLRA': 'Platanus racemosa',    # 加州梧桐
    'PONI': 'Populus nigra',        # 黑杨
    'PPTM': 'Populus tremula',      # 欧洲山杨
    'PPDE': 'Populus deltoides',    # 美洲黑杨
    'PPGR': 'Populus grandidentata', # 大齿杨
    'PPTR': 'Populus tremuloides',  # 美洲山杨
    'PSMA': 'Pseudotsuga macrocarpa', # 大果黄杉
    'PSME': 'Pseudotsuga menziesii', # 花旗松
    'RO': 'Robinia pseudoacacia',   # 刺槐
    'SAPC': 'Sapindus saponaria',   # 无患子
    'TADI': 'Taxodium distichum',   # 落羽杉
    'TAMU': 'Taxus mucronata',      # 墨西哥红豆杉
    'THOC': 'Thuja occidentalis',   # 北美香柏
    'THPL': 'Thuja plicata',        # 西部红柏
    'TICO': 'Tilia cordata',        # 小叶椴
    'TSCR': 'Tsuga canadensis',     # 加拿大铁杉
    'TSCA': 'Tsuga canadensis',     # 加拿大铁杉 
    'TSHE': 'Tsuga heterophylla',   # 西部铁杉
    'TSME': 'Tsuga mertensiana',    # 山铁杉
    
    # 墨西哥特有树种
    'PIAZ': 'Pinus arizonica',      # 亚利桑那松
    'PICM': 'Pinus cembroides',     # 墨西哥松
    'PIHR': 'Pinus hartwegii',      # 哈特韦格松
    'PIMZ': 'Pinus montezumae',     # 蒙特祖马松
    
    # 新增树种代码 - 从全球元数据提取
    'ABAL': 'Abies alba',           # 欧洲冷杉
    'ABBI': 'Abies bifolia',        # 双叶冷杉
    'ABBO': 'Abies borisii-regis',   # 保加利亚冷杉
    'ABCE': 'Abies cephalonica',    # 希腊冷杉
    'ABCI': 'Abies cilicica',       # 基利西亚冷杉
    'ABDE': 'Abies densa',          # 喜马拉雅冷杉
    'ABDU': 'Abies durangensis',    # 杜兰戈冷杉
    'ABFO': 'Abies forestii',       # 川滇冷杉
    'ABJA': 'Abies jaliscana',      # 哈利斯科冷杉
    'ABKO': 'Abies koreana',        # 朝鲜冷杉
    'ABNO': 'Abies nordmanniana',   # 诺德曼冷杉
    'ABPI': 'Abies pindrow',        # 长叶冷杉
    'ABPN': 'Abies pinsapo',        # 西班牙冷杉
    'ABPR': 'Abies procera',        # 高贵冷杉
    'ABRC': 'Abies recurvata',      # 西藏冷杉
    'ABSB': 'Abies spectabilis',    # 西喜冷杉
    'ABSP': 'Abies spp.',           # 冷杉属
    'ACSA': 'Acer saccharinum',     # 银枫
    'ADCO': 'Anadenanthera colubrina', # 穗花散尾葵
    'ADDI': 'Adansonia digitata',   # 猴面包树
    'ADHO': 'Adesmia horrida',      # 刺萼沙冬青
    'ADUS': 'Adesmia uspallatensis', # 乌斯帕拉塔沙冬青
    'AFXY': 'Afzelia xylocarpa',    # 柿格木
    'AGAU': 'Agathis australis',    # 南洋杉
    'AIOC': 'Aidia ochroleuca',     # 黄花茜树
    'ALAC': 'Alnus acuminata',      # 尖叶桤木
    'ALCR': 'Alnus viridis',        # 绿桤木
    'ALSP': 'Alnus spp.',           # 桤木属
    'ALTR': 'Alchornea triplinervia', # 三脉山麻杆
    'AMCE': 'Amburana cearensis',   # 香木
    'APMA': 'Apeiba macropetala',   # 大瓣猴面包树
    'ARAN': 'Araucaria angustifolia', # 巴西南洋杉
    'ARAR': 'Araucaria araucana',   # 智利南洋杉
    'ASCA': 'Acosmium cardenasii',  # 卡氏无香木
    'ASCS': 'Aspidosperma castroanum', # 卡斯特罗盾籽木
    'ASMU': 'Aspidosperma multiflorum', # 多花盾籽木
    'ASPO': 'Aspidosperma polyneuron', # 多脉盾籽木
    'ASPY': 'Aspidosperma pyrifolium', # 梨叶盾籽木
    'ASSU': 'Aspidosperma subincanum', # 亚光盾籽木
    'ASTO': 'Aspidosperma tomentosum', # 绒毛盾籽木
    'ATCU': 'Athrotaxis cupressoides', # 柏状蓬松柏
    'ATSE': 'Athrotaxis selaginoides', # 石松状蓬松柏
    'AUCH': 'Austrocedrus chilensis', # 智利南柏
    'BAPL': 'Baikiaea plurijuga',   # 多轭拜基木
    'BAPR': 'Baikiaea plurijuga',   # 多轭拜基木
    'BEAK': 'Betula papyrifera',    # 纸桦
    'BEAL': 'Betula alleghaniensis', # 阿勒格尼桦
    'BEER': 'Betula ermanii',       # 岳桦
    'BEPA': 'Betula papyrifera',    # 纸桦
    'BESP': 'Betula spp.',          # 桦木属
    'BEUT': 'Betula utilis',        # 高山桦
    'BRBO': 'Brachystegia boehmii',  # 波希米短蕊木
    'BRSP': 'Brachystegia spiciformis', # 穗状短蕊木
    'BUAF': 'Burkea africana',      # 非洲伯克木
    'BUGR': 'Bursera graveolens',   # 香脂树
    'CABU': 'Canthium burttii',     # 伯特茜树
    'CACO': 'Callitris columellaria', # 柱状赤柏松
    'CAIN': 'Callitris intratropica', # 热带内赤柏松
    'CANO': 'Callitropsis nootkatensis', # 黄柏
    'CAPY': 'Cariniana pyriformis',  # 梨形核果木
    'CARO': 'Callitris robusta',     # 粗壮赤柏松
    'CDAT': 'Cedrus atlantica',      # 阿特拉斯雪松
    'CDBR': 'Cedrus brevifolia',     # 短叶雪松
    'CDDE': 'Cedrus deodara',        # 喜马拉雅雪松
    'CEAN': 'Cedrela angustifolia',  # 窄叶洋椿
    'CECA': 'Cedrelinga cateniformis', # 链形洋椿
    'CEFI': 'Cedrela fissilis',      # 裂叶洋椿
    'CEMC': 'Centrolobium microchaete', # 小刺中果木
    'CEMO': 'Cedrela montana',       # 山地洋椿
    'CENE': 'Cedrela nebulosa',      # 云雾洋椿
    'CEOD': 'Cedrela odorata',       # 香椿
    'CESA': 'Cedrela salvadorensis', # 萨尔瓦多洋椿
    'CESP': 'Cedrela spp.',          # 洋椿属
    'CHAX': 'Choerospondias axillaris', # 南酸枣
    'CHOB': 'Chamaecyparis obtusa',   # 扁柏
    'CHTH': 'Chamaecyparis thyoides', # 大西洋柏木
    'CKTA': 'Chukrasia tabularis',    # 麻楝
    'CMJA': 'Cryptomeria japonica',   # 日本柳杉
    'CNPL': 'Cenostigma pluviosum',   # 雨生假决明
    'COLU': 'Copaifera lucens',       # 发光古巴香脂树
    'COPA': 'Corynanthe paniculata',  # 圆花冠木
    'CPBE': 'Carpinus betulus',       # 欧洲鹅耳枥
    'CUCH': 'Cupressus chengiana',    # 岷江柏木
    'CYTE': 'Carya texana',           # 德克萨斯山核桃
    'DABI': 'Dacrydium biforme',      # 双形鸡毛松
    'DACO': 'Dacrydium colensoi',     # 科伦索鸡毛松
    'DRLO': 'Dracophyllum longifolium', # 长叶龙血树
    'DRSP': 'Drypetes sp.',           # 核果木属
    'ENCY': 'Entandrophragma cylindricum', # 柱状花脉木
    'ERAF': 'Erythrophleum africanum',  # 非洲红皮木
    'ERIV': 'Erythrophloeum ivorense',  # 象牙红皮木
    'FAOR': 'Fagus orientalis',        # 东方山毛榉
    'FICU': 'Fitzroya cupressoides',   # 柏状费氏柏
    'FOHO': 'Fokienia hodginsii',      # 福建柏
    'FRAM': 'Fraxinus americana',      # 美国白蜡树
    'FREX': 'Fraxinus excelsior',      # 欧洲白蜡树
    'FRNI': 'Fraxinus nigra',          # 黑白蜡树
    'GEAM': 'Genipa americana',        # 美洲梳树
    'GOGL': 'Goupia glabra',           # 光滑古匹树
    'HABI': 'Halocarpus biformis',     # 双形盐果木
    'HAIM': 'Handroanthus impetiginosus', # 粉红风铃木
    'HAIP': 'Handroanthus impetiginosus', # 粉红风铃木
    'HAOC': 'Handroanthus ochraceus',  # 黄花风铃木
    'HASE': 'Handroanthus serratifolius', # 锯叶风铃木
    'HEFO': 'Heritiera fomes',         # 红树荷树
    'HEHE': 'Hedera helix',            # 常春藤
    'HUCR': 'Hura crepitans',          # 砂果树
    'HUPR': 'Humiriastrum procerum',   # 高大湿地木
    'HYCO': 'Hymenaea courbaril',      # 美洲乳香树
    'HYST': 'Hymenaea stigonocarpa',   # 柱头美洲乳香树
    'JACO': 'Jacaranda copaia',        # 蓝花楹
    'JGAU': 'Juglans australis',       # 南方胡桃
    'JGNE': 'Juglans neotropica',      # 新热带胡桃
    'JGNI': 'Juglans nigra',           # 黑胡桃
    'JUCO': 'Juniperus communis',      # 欧洲刺柏
    'JUEX': 'Juniperus excelsa',       # 高大刺柏
    'JUFO': 'Juniperus foetidissima',  # 臭柏
    'JUPC': 'Juniperus procera',       # 非洲铅笔柏
    'JUPH': 'Juniperus phoenicea',     # 腓尼基刺柏
    'JUPR': 'Juniperus przewalskii',   # 祁连圆柏
    'JURE': 'Juniperus recurva',       # 垂枝刺柏
    'JUSP': 'Juniperus spp.',          # 刺柏属
    'JUTI': 'Juniperus tibetica',      # 西藏刺柏
    'JUTU': 'Juniperus turkestanica',  # 突厥刺柏
    'LAGM': 'Larix gmelinii',          # 兴安落叶松
    'LAGR': 'Larix griffithiana',      # 喜马拉雅落叶松
    'LASI': 'Larix sibirica',          # 西伯利亚落叶松
    'LASP': 'Larix spp.',              # 落叶松属
    'LGCO': 'Lagarostrobus colensoi',  # 科伦索南洋杉
    'NEOP': 'Nectandra oppositifolia', # 对叶油樟
    'NOBE': 'Nothofagus betuloides',   # 桦叶假山毛榉
    'NOGU': 'Nothofagus gunnii',       # 冈恩假山毛榉
    'NOME': 'Nothofagus menziesii',    # 门兹假山毛榉
    'NOPU': 'Nothofagus pumilio',      # 矮小假山毛榉
    'NOSO': 'Nothofagus solanderi',    # 索兰德假山毛榉
    'PAPR': 'Parkinsonia praecox',     # 早花帕金森木
    'PCCH': 'Picea chihuahuana',       # 奇瓦瓦云杉
    'PCGN': 'Picea glehnii',           # 黑云杉
    'PCLI': 'Picea likiangensis',      # 丽江云杉
    'PCOB': 'Picea obovata',           # 西伯利亚云杉
    'PCOM': 'Picea omorika',           # 塞尔维亚云杉
    'PCOR': 'Picea orientalis',        # 东方云杉
    'PCSH': 'Picea schrenkiana',       # 天山云杉
    'PCSM': 'Picea smithiana',         # 喜马拉雅云杉
    'PCSN': 'Picea spinulosa',         # 刺云杉
    'PCSP': 'Picea spp.',              # 云杉属
    'PCTI': 'Picea tienschanica',      # 天山云杉
    'PEEL': 'Pericopsis elata',        # 高非洲紫檀
    'PHAL': 'Phyllocladus alpinus',    # 高山叶柄杉
    'PHAS': 'Phyllocladus aspleniifolius', # 蕨叶叶柄杉
    'PHGL': 'Phyllocladus glaucus',    # 灰绿叶柄杉
    'PHTR': 'Phyllocladus trichomanoides', # 毛蕨叶柄杉
    'PIAM': 'Pinus armandii',          # 华山松
    'PIBR': 'Pinus brutia',            # 布鲁提亚松
    'PICH': 'Pinus leiophylla',        # 光叶松
    'PICL': 'Pinus coulteri',          # 库尔特松
    'PICU': 'Pinus culminicola',       # 顶生松
    'PIDE': 'Pinus densiflora',        # 赤松
    'PIEL': 'Pinus elliottii',         # 湿地松
    'PIEN': 'Pinus engelmannii',       # 恩格曼松
    'PIGE': 'Pinus gerardiana',        # 吉拉尔德松
    'PIGR': 'Pinus greggii',           # 格雷格松
    'PIHA': 'Pinus halepensis',        # 阿勒颇松
    'PIHE': 'Pinus heldreichii',       # 赫尔德莱希松
    'PIKE': 'Pinus kesiya',            # 思茅松
    'PIKO': 'Pinus koraiensis',        # 红松
    'PILE': 'Pinus leucodermis',       # 白皮松
    'PILR': 'Pinus laricio',           # 科西嘉黑松
    'PIMA': 'Pinus massoniana',        # 马尾松
    'PIMG': 'Pinus mugo',              # 高山松
    'PIMK': 'Pinus merkusii',          # 马尾松
    'PIMO': 'Pinus monophylla',        # 单叶松
    'PIMT': 'Picea martinezii',        # 马丁内兹云杉
    'PIMU': 'Pinus mughus',            # 矮松
    'PIMX': 'Picea mexicana',          # 墨西哥云杉
    'PINL': 'Pinus nelsonii',          # 尼尔森松
    'PIOO': 'Pinus oocarpa',           # 卵果松
    'PIPC': 'Pinus pinceana',          # 平斯松
    'PIPE': 'Pinus peuce',             # 巴尔干五针松
    'PIPS': 'Pinus pseudostrobus',     # 伪strobus松
    'PIPT': 'Pinus patula',            # 墨西哥松
    'PIRO': 'Pinus roxburghii',        # 长叶松
    'PIRU': 'Pinus rudis',             # 粗糙松
    'PISI': 'Pinus sibirica',          # 西伯利亚松
    'PITB': 'Pinus tabulaeformis',     # 油松
    'PITE': 'Pinus teocote',           # 特奥科特松
    'PITW': 'Pinus taiwanensis',       # 台湾松
    'PIUN': 'Pinus uncinata',          # 钩状松
    'PIWA': 'Pinus wallichiana',       # 喜马拉雅长叶松
    'PIYU': 'Pinus yunnanensis',       # 云南松
    'PLOC': 'Platanus occidentalis',   # 美国悬铃木
    'PLUV': 'Pilgerodendron uviferum', # 葡萄果皮尔格木
    'POPY': 'Poincianella pyramidalis', # 金凤花
    'PORO': 'Polylepis rodolfovasquezii', # 多鳞木
    'POTA': 'Polylepis tarapacana',    # 塔拉帕卡纳多鳞木
    'PPBA': 'Populus balsamifera',     # 香杨
    'PPCI': 'Populus ciliata',         # 缘毛杨
    'PPFR': 'Populus fremontii',       # 弗里蒙特杨
    'PRBA': 'Prioria balsamifera',     # 香脂波罗格木
    'PRMA': 'Previa maxima',           # 大普列维亚
    'PROS': 'Prosopis spp.',           # 洋槐属
    'PSCO': 'Pseudowintera colorata',  # 彩冬青
    'PSSI': 'Pseudotsuga sinensis',    # 黄杉
    'PTAN': 'Pterocarpus angolensis',  # 安哥拉紫檀
    'PTLE': 'Pistacia lentiscus',      # 乳香黄连木
    'QUAF': 'Quercus afares',          # 阿法雷斯栎
    'QUBN': 'Quercus boyntonii',       # 博因顿栎
    'QUCA': 'Quercus canariensis',     # 加那利栎
    'QUCE': 'Quercus cerris',          # 土耳其栎
    'QUFG': 'Quercus faginea',         # 葡萄牙栎
    'QUFR': 'Quercus frainetto',       # 匈牙利栎
    'QUGA': 'Quercus gambelii',        # 冈贝尔栎
    'QUHA': 'Quercus hartwissiana',    # 哈特威斯栎
    'QUKE': 'Quercus kelloggii',       # 加州黑栎
    'QULI': 'Qualea lineata',          # 线纹夸里木
    'QUMC': 'Quercus macrolepis',      # 大鳞栎
    'QUMO': 'Quercus mongolica',       # 蒙古栎
    'QUPR': 'Quercus prinus',          # 栗栎
    'QUPU': 'Quercus pubescens',       # 绒毛栎
    'QUSU': 'Quercus suber',           # 栓皮栎
    'RHCM': 'Rhododendron campanulatum', # 钟花杜鹃
    'SALA': 'Salix lanata',            # 绒毛柳
    'SASP': 'Salix spp.',              # 柳属
    'SCBR': 'Schinopsis brasiliensis', # 巴西红木
    'SCBU': 'Scutia buxifolia',        # 黄杨叶盾刺
    'SEGI': 'Sequoiadendron giganteum', # 巨杉
    'SISA': 'Simira salvadorensis',    # 萨尔瓦多西米拉
    'SOAP': 'Sonneratia apetala',      # 无瓣海桑
    'SOCH': 'Sophora chrysophylla',    # 金叶槐
    'SWMC': 'Swietenia macrophylla',   # 大叶桃花心木
    'TAAU': 'Tabebuia aurea',          # 金风铃木
    'TABA': 'Taxus baccata',           # 欧洲红豆杉
    'TEGR': 'Tectona grandis',         # 柚木
    'TEPA': 'Tetragastris panamensis', # 巴拿马四腹果
    'TESI': 'Tetracentron sinense',    # 水青树
    'TESU': 'Terminalia superba',      # 高大诺木
    'TOCI': 'Toona ciliata',           # 红椿
    'TRSC': 'Triplochiton schleroxylon', # 非洲轻木
    'TRSL': 'Triplochiton scleroxylon', # 非洲轻木
    'TRTU': 'Trichilia tuberculata',   # 结节赤杨
    'TSDI': 'Tsuga diversifolia',      # 多变铁杉
    'TSDU': 'Tsuga dumosa',            # 喜马拉雅铁杉
    'ULSP': 'Ulmus spp.',              # 榆属
    'ULWA': 'Ulmus wallichiana',       # 瓦立榆
    'VIKE': 'Vitex keniensis',         # 肯尼亚牡荆
    'WICE': 'Widdringtonia cedarbergensis', # 雪松山南非柏
    'XYWI': 'Xylopia wilwerthii',      # 维尔沃特香木兰
    'ZETU': 'Zeyheria tuberculosa',    # 结节泽海树
} 